### PR TITLE
Added a flag for all functions to return results first in first out, …

### PR DESCRIPTION
**Pull request by guyluz11**
…changed example file values to scan more, and started port scan from 1 to solve windows scan error on port 0

### CODE REVIEW

**Comment by guyluz11** [comment]
Fix for #17 
#14 and #10 leftover in the example.

**Comment by guyluz11** [comment]
Forgot to mention that I have added `universal_io`  #20

**Comment by guyluz11** [comment]
Updated the pr, please test it on your network to make suer it runs smoothly.
My main concern is running by default `PortScanner.discover` on all 65535 ports, I have opened an issue as it crashed on my Windows machine.
Please test if it does not crash when you run it.
Would love to get feedback on what OS did you tested it on.

**Comment by git-elliot** [comment]
I'm getting open file limit in my system. Last port which failed to connect was 9689, although it randomly giving error for any port number above 9400. I'm consistently able to scan from 1 to 9400. 
```
Unhandled exception:
SocketException: Connection failed (OS Error: Too many open files, errno = 24), address = 192.168.1.1, port = 9689
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:940:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1796:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2019:22)
#5      Socket.connect (dart:io/socket.dart:770:21)
#6      PortScanner.connectToPort (package:network_tools/src/port_scanner.dart:156:37)
#7      PortScanner.customDiscover (package:network_tools/src/port_scanner.dart:87:13)
<asynchronous suspension>
```

**Pull request merged**
