### PR TITLE
Fix issue #40 and #3

### PR DESCRIPTION
**Pull request by guyluz11**
#40 
#3

### CODE REVIEW

**Comment by guyluz11** [comment]
Not sure why all the old commits got here but most of it is stuff that got merged before.

Accidentally wrote in one commit fix for # 3. It was suppose to be Fix for # 40.

**Comment by guyluz11** [comment]
I have added fox for #3 as well.

**Comment by guyluz11** [comment]
> > Not sure why all the old commits got here
> 
> Because we haven't merged dev into main, maybe that's why it's showing all the previous commits.

This pr is to dev branch so probably it is other reason.

**Comment by git-elliot** [comment]
Seems like this by design, but have some workaround. Although no harm, let it be like this. Source - [GitHub pull request showing commits that are already in target branch](https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch)

**Comment by guyluz11** [comment]
I've added another feature here so I should also update the version and the change log.
You can check everything else in the meantime.

**Pull request merged**
